// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tstnfgiazoqfsrmtevgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzdG5mZ2lhem9xZnNybXRldmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2OTI3MjcsImV4cCI6MjA1NzI2ODcyN30.6RRxX5Um0ljVhvaI33phmDkxI6YAkWXF7hj9gWi5Lyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);